apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/nachopavon/Downloads/kompose-darwin-amd64 convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: my-financial
  name: my_financial
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    io.kompose.service: my-financial
status:
  loadBalancer: {}
