apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/nachopavon/Downloads/kompose-darwin-amd64 convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/nachopavon/Downloads/kompose-darwin-amd64 convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: rabbitmq
    spec:
      containers:
        - image: rabbitmq:management
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "5672"
            failureThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 15
          name: rabbitmq
          ports:
            - containerPort: 15672
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
status: {}
